config/routes.rb
require_relative "../app/controllers/conversion_controller"

Rails.application.routes.draw do
  get "/", to: "conversions#index"
  get "/convert", to: "conversions#convert"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversion_controller.rb
require_relative "../services/unit_converter/unit_converter"

class ConversionsController < ApplicationController
  def index
  end

  def convert
    query = params[:q]
    result = UnitConverterService.convert(query)

    if result
      @converted_value = result
      respond_to do |format|
        format.html { render :index, status: :ok }
        format.text { render plain: result }
      end
    else
      @error = "Invalid query"
      respond_to do |format|
        format.html { render :index, status: :bad_request }
        format.text { render plain: "Invalid query" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversions/index.html.erb
<h1>Unit Converter</h1>
<p>Enter a query in the format "1 kg in lb":</p>

<%= form_tag convert_path, method: :get do %>
  <%= label_tag :query %>
  <%= text_field_tag :q %>
  <%= submit_tag "Convert" %>
<% end %>

<% if @converted_value %>
  <p>Converted value:</p>
  <p><%= @converted_value %></p>
<% elsif @error %>
  <p><%= @error %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnitConverter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>